### Send POST request with json body
POST http://localhost:8080/api/v1/create
Content-Type: application/json

{"name" : "Oleg","age": 30,"friends": [1,2,3]}


### Send POST request with json body
POST http://localhost:8080/api/v1/create
Content-Type: application/json

{"name": "Ivan", "age": 21, "friends": [2,3]}

### Send POST request with json body
POST http://localhost:8080/api/v1/create
Content-Type: application/json

{"name": "Vasya", "age": 27, "friends": []}

### Send POST request with json body
POST http://localhost:8080/api/v1/create
Content-Type: application/json

{"name": "Gena", "age": 25, "friends": []}

### GET request with a header
GET http://localhost:8080/api/v1/friends/1
Accept: application/json

### GET request with a header
GET http://localhost:8080/api/v1/friends/2
Accept: application/json

### GET request with a header
GET http://localhost:8080/api/v1/friends/4
Accept: application/json

### Send POST request with json body
POST http://localhost:8080/api/v1/make_friends
Content-Type: application/json

{"source_id": 1,"target_id": 2}

### Send POST request with json body
POST http://localhost:8080/api/v1/make_friends
Content-Type: application/json

{"source_id": 2,"target_id": 4}

### Send POST request with json body
DELETE http://localhost:8080/api/v1/user
Content-Type: application/json

{"target_id": 4}

### Send POST request with json body
PATCH http://localhost:8080/api/v1/2
Content-Type: application/json

{"new age": 28}