version: "3.8"

services:
  backend:
    restart: always
    build: ./
    expose:
      - 8000
    command: ["/app/server"]
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: databasePsql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  nginx:
    build: nginx
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - backend
volumes:
  postgres_data: